"""add_composite_indexes

Revision ID: 1d1baf6cebcc
Revises: a74d5ecdcbbd
Create Date: 2025-12-02 11:34:09.444521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d1baf6cebcc'
down_revision: Union[str, Sequence[str], None] = 'a74d5ecdcbbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_audit_logs_tenant_timestamp', 'audit_logs', ['tenant_id', 'timestamp'], unique=False)
    op.create_index('ix_token_usage_tenant_reported', 'token_usage', ['tenant_id', 'reported_to_stripe'], unique=False)
    op.create_index('ix_token_usage_tenant_timestamp', 'token_usage', ['tenant_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_token_usage_tenant_timestamp', table_name='token_usage')
    op.drop_index('ix_token_usage_tenant_reported', table_name='token_usage')
    op.drop_index('ix_audit_logs_tenant_timestamp', table_name='audit_logs')
    # ### end Alembic commands ###
