"""add_key_prefix_column

Revision ID: 7f6cf943f5fd
Revises: 1d1baf6cebcc
Create Date: 2026-02-10 06:10:32.355909

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f6cf943f5fd"
down_revision: Union[str, Sequence[str], None] = "1d1baf6cebcc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("api_keys", sa.Column("key_prefix", sa.String(length=8), nullable=True))
    op.create_index(op.f("ix_api_keys_key_prefix"), "api_keys", ["key_prefix"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_api_keys_key_prefix"), table_name="api_keys")
    op.drop_column("api_keys", "key_prefix")
    # ### end Alembic commands ###
