"""add_reported_to_stripe

Revision ID: a74d5ecdcbbd
Revises: 907236a277b9
Create Date: 2025-12-02 11:24:31.615785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a74d5ecdcbbd'
down_revision: Union[str, Sequence[str], None] = '907236a277b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_usage', sa.Column('reported_to_stripe', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_token_usage_reported_to_stripe'), 'token_usage', ['reported_to_stripe'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_usage_reported_to_stripe'), table_name='token_usage')
    op.drop_column('token_usage', 'reported_to_stripe')
    # ### end Alembic commands ###
