"""add_multi_tenancy_support

Revision ID: ea3c4d930566
Revises: a1b2c3d4e5f6_token_usage
Create Date: 2025-11-19 11:41:24.197949

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from app import models

# revision identifiers, used by Alembic.
revision: str = "ea3c4d930566"
down_revision: Union[str, Sequence[str], None] = "a1b2c3d4e5f6_token_usage"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", models.GUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("plan", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_tenant_created", "tenants", ["created_at"], unique=False)
    op.create_index("ix_tenant_slug", "tenants", ["slug"], unique=False)
    op.create_index(op.f("ix_tenants_slug"), "tenants", ["slug"], unique=True)

    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", models.GUID(), nullable=False))
        batch_op.alter_column(
            "id", existing_type=sa.NUMERIC(), type_=models.GUID(), existing_nullable=False
        )
        batch_op.alter_column(
            "customer_id", existing_type=sa.NUMERIC(), type_=models.GUID(), existing_nullable=False
        )
        batch_op.create_index(op.f("ix_api_keys_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_foreign_key(
            "fk_api_keys_tenant_id_tenants", "tenants", ["tenant_id"], ["id"]
        )

    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", models.GUID(), nullable=False))
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.Integer(),
            existing_nullable=False,
            autoincrement=True,
        )
        batch_op.alter_column(
            "request_id", existing_type=sa.NUMERIC(), type_=models.GUID(), existing_nullable=False
        )
        batch_op.alter_column(
            "api_key_id", existing_type=sa.NUMERIC(), type_=models.GUID(), existing_nullable=False
        )
        batch_op.create_index(op.f("ix_audit_logs_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_foreign_key(
            "fk_audit_logs_tenant_id_tenants", "tenants", ["tenant_id"], ["id"]
        )

    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", models.GUID(), nullable=False))
        batch_op.alter_column(
            "id", existing_type=sa.NUMERIC(), type_=models.GUID(), existing_nullable=False
        )
        batch_op.create_index(op.f("ix_customers_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_foreign_key(
            "fk_customers_tenant_id_tenants", "tenants", ["tenant_id"], ["id"]
        )

    with op.batch_alter_table("token_usage", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", models.GUID(), nullable=False))
        batch_op.alter_column(
            "request_id", existing_type=sa.NUMERIC(), type_=models.GUID(), existing_nullable=False
        )
        batch_op.alter_column(
            "api_key_id", existing_type=sa.NUMERIC(), type_=models.GUID(), existing_nullable=False
        )
        batch_op.drop_index("ix_token_usage_request_id")
        batch_op.create_index(op.f("ix_token_usage_request_id"), ["request_id"], unique=True)
        batch_op.create_index(op.f("ix_token_usage_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_foreign_key(
            "fk_token_usage_tenant_id_tenants", "tenants", ["tenant_id"], ["id"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "token_usage", type_="foreignkey")
    op.drop_index(op.f("ix_token_usage_tenant_id"), table_name="token_usage")
    op.drop_index(op.f("ix_token_usage_request_id"), table_name="token_usage")
    op.create_index(op.f("ix_token_usage_request_id"), "token_usage", ["request_id"], unique=False)
    op.alter_column(
        "token_usage",
        "api_key_id",
        existing_type=models.GUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "token_usage",
        "request_id",
        existing_type=models.GUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.drop_column("token_usage", "tenant_id")
    op.drop_constraint(None, "customers", type_="foreignkey")
    op.drop_index(op.f("ix_customers_tenant_id"), table_name="customers")
    op.alter_column(
        "customers", "id", existing_type=models.GUID(), type_=sa.NUMERIC(), existing_nullable=False
    )
    op.drop_column("customers", "tenant_id")
    op.drop_constraint(None, "audit_logs", type_="foreignkey")
    op.drop_index(op.f("ix_audit_logs_tenant_id"), table_name="audit_logs")
    op.alter_column(
        "audit_logs",
        "api_key_id",
        existing_type=models.GUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "audit_logs",
        "request_id",
        existing_type=models.GUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "audit_logs",
        "id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_column("audit_logs", "tenant_id")
    op.drop_constraint(None, "api_keys", type_="foreignkey")
    op.drop_index(op.f("ix_api_keys_tenant_id"), table_name="api_keys")
    op.alter_column(
        "api_keys",
        "customer_id",
        existing_type=models.GUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "api_keys", "id", existing_type=models.GUID(), type_=sa.NUMERIC(), existing_nullable=False
    )
    op.drop_column("api_keys", "tenant_id")
    op.drop_index(op.f("ix_tenants_slug"), table_name="tenants")
    op.drop_index("ix_tenant_slug", table_name="tenants")
    op.drop_index("ix_tenant_created", table_name="tenants")
    op.drop_table("tenants")
    # ### end Alembic commands ###
